service: this-is-the-name-of-the-service

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

provider:
  name: aws
  runtime: nodejs8.10

functions:

  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello